### ISSUE TITLE
Add preview images

### ISSUE THREAD

**Issue by Arcanemagus** [lee-dohm/atom-style-tweaks#74]
Although snippets like this are pretty quick to test out, people (like me) are lazy and would rather stare at a pretty picture before going through that effort.

Add the ability to include a preview image with style snippets.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/lee-dohm/atom-style-tweaks), this project is no longer maintained and has been retired. Because of this, I am [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
