### ISSUE TITLE
Mobile formatting is broken

### ISSUE THREAD

**Issue by lee-dohm** [lee-dohm/atom-style-tweaks#78]
Reported by @pixilz regarding https://www.atom-tweaks.com/about

**Comment by pixilz** [comment]
So it looks like the main culprit of this is `Primer` which is setup to only go down to `980px`. A temporary solution until `Primer` has been revamped would be to set all containers to have:
```
.container {
    max-width: 980px;
    width: 100%;
}
```

On top of that you will be left with `10px` of extra horizontal spacing from the negative margins on the columns. Since that space will always be blank on mobile it _could_ be simple enough to just add:
```
body {
    overflow-x: hidden;
}
```

That being said a `10px` scrollbar may be fine for now due to the possible issues that can arise with a hidden overflow on the body. (Such as items that aren't obviously larger than the viewport's width.)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/lee-dohm/atom-style-tweaks), this project is no longer maintained and has been retired. Because of this, I am [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
